# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 20:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upeu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departamento',
            old_name='capital',
            new_name='ciudad_capital',
        ),
    ]
