# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upeu', '0002_auto_20160125_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6, unique=True)),
                ('nombre_provincia', models.CharField(max_length=100)),
                ('ciudad_capital', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(max_length=1)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upeu.Departamento')),
            ],
        ),
    ]
