# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upeu', '0005_tipo_universidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_ent_acad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_entidad', models.CharField(max_length=100, unique=True)),
                ('abreviatura', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('conector', models.CharField(blank=True, max_length=20, null=True)),
                ('estado', models.CharField(max_length=1)),
            ],
        ),
    ]
