# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 22:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upeu', '0006_tipo_ent_acad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entidad_academica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_entidad', models.CharField(blank=True, max_length=20, null=True)),
                ('lugar_conocido', models.CharField(blank=True, help_text='Lugar de ubicacion como es conocida', max_length=100, null=True)),
                ('eslogan', models.TextField(blank=True, max_length=100, null=True)),
                ('mision', models.TextField(blank=True, max_length=2000, null=True)),
                ('vision', models.TextField(blank=True, max_length=2000, null=True)),
                ('estado', models.CharField(max_length=1)),
                ('distrito', models.ForeignKey(blank=True, help_text='Aplica universidad, lugar donde esta ubicada', null=True, on_delete=django.db.models.deletion.CASCADE, to='upeu.Distrito')),
                ('entidad_padre', models.ForeignKey(blank=True, help_text='A quien pertenece', null=True, on_delete=django.db.models.deletion.CASCADE, to='upeu.Entidad_academica')),
                ('tipo_entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upeu.Tipo_ent_acad')),
                ('tipo_universidad', models.ForeignKey(blank=True, help_text='Aplica solo a universidades', null=True, on_delete=django.db.models.deletion.CASCADE, to='upeu.Tipo_universidad')),
            ],
        ),
    ]
