# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre', max_length=60, verbose_name='Nombre')),
                ('nombres', models.CharField(blank=True, help_text='Otros nombres', max_length=120, null=True, verbose_name='Nombres')),
                ('apepat', models.CharField(max_length=120, verbose_name='Apellido paterno')),
                ('apemat', models.CharField(max_length=120, verbose_name='Apellido materno')),
                ('fecha_nac', models.DateField(verbose_name='Fecha de nacimiento')),
                ('sexo', models.CharField(max_length=1, verbose_name='Sexo')),
                ('direccion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección actual')),
                ('celular', models.CharField(blank=True, max_length=12, null=True, verbose_name='Celular')),
                ('estado', models.CharField(max_length=1, verbose_name='Estado')),
                ('fecha_hora_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
