# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 17:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno_uni',
            fields=[
                ('alumno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='academico.Persona')),
                ('codigo_universitario', models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='Código universitario')),
                ('estado', models.CharField(max_length=1, verbose_name='Estado')),
            ],
        ),
    ]
