# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_alumno_uni'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_periodo', models.CharField(max_length=30, unique=True, verbose_name='Nombre del periodo')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicial')),
                ('fecha_final', models.DateField(verbose_name='Fecha final')),
                ('abierto', models.CharField(help_text='Use 1 parar abierto, 0 para cerrado', max_length=1, verbose_name='Cerrado')),
                ('estado', models.CharField(max_length=1, verbose_name='Estado')),
            ],
        ),
    ]
