# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0004_auto_20160126_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.DecimalField(decimal_places=0, max_digits=2, unique=True, verbose_name='Número')),
                ('numero_letras', models.DateField(blank=True, null=True, unique=True, verbose_name='Número en letra')),
                ('numero_romano', models.DateField(blank=True, null=True, unique=True, verbose_name='Número en romano')),
                ('estado', models.CharField(max_length=1, verbose_name='Estado')),
            ],
        ),
    ]
