# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 15:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0005_ciclo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ciclo',
            name='numero_letras',
        ),
        migrations.RemoveField(
            model_name='ciclo',
            name='numero_romano',
        ),
    ]
