# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0006_auto_20160126_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciclo',
            name='numero_letras',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Número en letra'),
        ),
        migrations.AddField(
            model_name='ciclo',
            name='numero_romano',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True, verbose_name='Número en romano'),
        ),
    ]
