# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0007_auto_20160126_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_area', models.CharField(max_length=100, unique=True, verbose_name='Nombre del área')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('estado', models.CharField(max_length=1, verbose_name='Estado')),
            ],
        ),
    ]
