# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0008_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_curso', models.CharField(max_length=200, unique=True, verbose_name='Nombre del curso')),
                ('abreviatura', models.CharField(blank=True, max_length=30, null=True, verbose_name='Abreviatura del curso')),
                ('estado', models.CharField(max_length=1, verbose_name='Estado')),
                ('area', models.ForeignKey(on_delete='id', to='academico.Area')),
            ],
        ),
    ]
