# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0009_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.Area'),
        ),
    ]
