# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 16:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0011_auto_20160126_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan_acad_curso',
            name='thp',
        ),
    ]
