# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lugar_examen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_lugar', models.CharField(max_length=120)),
                ('direccion', models.CharField(max_length=150)),
                ('referencia', models.CharField(max_length=200)),
            ],
        ),
    ]
