# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 22:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admision', '0003_modalidad_examen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fechas_examen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_examen', models.DateField()),
                ('descripcion', models.TextField()),
                ('modalidad_examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admision.Modalidad_examen')),
            ],
        ),
    ]
