# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admision', '0004_fechas_examen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
    ]
