# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admision', '0009_auto_20160120_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_documento',
            name='descripcion',
            field=models.CharField(blank=True, help_text='Ingrese una descripción', max_length=100, null=True, verbose_name='Descripción'),
        ),
    ]
