# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 15:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admision', '0010_auto_20160120_0848'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta_examen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres_apellidos', models.CharField(help_text='Nombres y apellidos completos', max_length=200, verbose_name='Nombres y apellidos')),
                ('numero_doc', models.CharField(max_length=20, unique=True, verbose_name='Número de documento')),
                ('edad', models.PositiveIntegerField(help_text='Ingrese sus años cumplidos', verbose_name='Edad')),
                ('grado', models.CharField(help_text='5to grado, secundaria completa, Bachiller, etc.', max_length=100, verbose_name='Grado de estudios')),
                ('coleg_acad_igles', models.CharField(blank=True, help_text='Referencial', max_length=200, null=True, verbose_name='Colegio/Academia/Igleisa')),
                ('celular', models.CharField(help_text='Teléfono de contacto', max_length=16, verbose_name='N° de celular')),
                ('correo', models.CharField(max_length=100, unique=True, verbose_name='Correo electrónico')),
                ('fecha_hora_registro', models.DateTimeField(default=datetime.datetime.now)),
                ('fechas_examen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admision.Fechas_examen')),
                ('lugar_examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admision.Lugar_examen')),
                ('modalidad_estudio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admision.Modalidad_estudio')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admision.Tipo_documento')),
            ],
        ),
    ]
