# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='opcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_opcion', models.CharField(max_length=120)),
                ('url', models.CharField(max_length=300)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
    ]
